// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../src/components/Application/src/AppProvider.vue')['default']
    HeaderTop: typeof import('./../src/components/Application/src/HeaderTop.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
  }
}

export { }
